export const START = "START";
export const DISPLAY_ACCOUNTS_ACTION = "DISPLAY_ACCOUNTS";
export const DISPLAY_ADD_ACCOUNTS_ACTION = "DISPLAY_ADD_ACCOUNTS";
export const ADD_NEW_ACCOUNT = "ADD_NEW_ACCOUTN";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";